contact_links:
- name: "Crash bug"
  url: https://https://github.com/openbmc/docs/blob/master/security/obmc-security-response-team.md
  about: "Please file any bug causing a crash to openbmc-security@lists.ozlabs.org."
